server:
  port: 8080
spring:
    application:
        name: reward-points-system
    datasource:
      type: com.zaxxer.hikari.HikariDataSource
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/reward-point-system?useUnicode=true&characterEncoding=utf-8&useSSL=false
      username: root
      password: 123

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
